//  Generated by relay-snapshot-test-generator
import React from 'react';
import App from '../App';
import {createMockEnvironment, MockPayloadGenerator} from 'relay-test-utils';
import ReactTestRenderer from 'react-test-renderer';
import {QueryRenderer, graphql} from 'react-relay';

test('App.test Render State', () => {
  const environment = createMockEnvironment();
  const renderer = ReactTestRenderer.create(<App environment={environment} />);
  environment.mock.resolveMostRecentOperation(operation =>
    MockPayloadGenerator.generate(operation),
  );
  expect(renderer).toMatchSnapshot();
});
