//  Generated by relay-snapshot-test-generator
import React from 'react';
import HomeScreen from '../screens/HomeScreen';
import {createMockEnvironment, MockPayloadGenerator} from 'relay-test-utils';
import ReactTestRenderer from 'react-test-renderer';

test('HomeScreen.test Render State', () => {
  const environment = createMockEnvironment();
  const renderer = ReactTestRenderer.create(
    <HomeScreen environment={environment} />,
  );
  environment.mock.resolveMostRecentOperation(operation =>
    MockPayloadGenerator.generate(operation),
  );
  expect(renderer).toMatchSnapshot();
});
