const EN = {
  id_app: 'My App',
  id_profile_view_profile: 'View Profile',
  id_profile_title: 'YOU',
  id_profile_general: 'General',
  id_profile_general_groups: 'Groups',
  id_profile_general_bookmarks: 'Bookmarks',
  id_profile_general_shelves: 'Shelves',
  id_profile_general_stats: 'Stats',
  id_profile_general_events: 'Events',
  id_profile_settings: 'Settings',
  id_profile_settings_customize_interests: 'Customize interests',
  id_profile_help: 'Help',
  id_profile_terms_of_service: 'Terms of service',
  id_profile_privacy_policy: 'Privacy Policy',
  id_screen_groups_title: 'GROUPS',
  id_screen_bookmarks_title: 'BOOKMARKS',
  id_screen_stats_title: 'STATS',
  id_search_placeholder: 'Title, Author, ISBN',
  id_shelves_left_tab: 'Shelves',
  id_shelves_center_tab: 'Discover',
  id_shelves_right_tab: 'Create',
};

export default EN;
